name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.1
  
  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  
  # Charts for admin dashboard
  fl_chart: ^0.66.0
  
  # UI/UX
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.3.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true